#!/usr/bin/env bash
# Bash script that will display information about subdomains.

get_subdomains() {
	domain="$1"
	subdomain="$2"
	default=("www" "lb-01" "web-01" "web-02")

	if [ -z "$subdomain" ]; then
		for sub in "${default[@]}"; do
			subdomain=$sub
			dest=$(dig +short "$sub"."$domain")
			record=$(dig "$sub"."$domain" | awk 'NR == 14 {print $4}')
			echo "The subdomain $sub is a $record record and points to $dest"
		done
	else
		dest=$(dig +short "$subdomain"."$domain")
		record=$(dig "$subdomain"."$domain" | awk 'NR == 14 {print $4}')
		echo "The subdomain $subdomain is a $record record and points to $dest"
	fi
}

main() {
	get_subdomains "$1" "$2"
}
main "$@"
