#!/usr/bin/env bash
# Configure Nginx to add custom response header
sudo apt update 
sudo apt install nginx -y
echo "add_header X-Served-By \$hostname;" > /etc/nginx/conf.d/custom_header.conf
systemctl restart nginx
