#!/usr/bin/env bash
# Bash script that kill a process
terminate_script() {
    echo "I hate the kill command"
    rm -f /var/run/myscript.pid
    exit 0
}

echo "$$" > /var/run/myscript.pid

trap 'terminate_script' SIGTERM SIGQUIT
trap 'echo "Y U no love me?!"' SIGINT

while true; do
    echo "To infinity and beyond indefinitely"
    sleep 2
done

