#!/usr/bin/env bash
# this Bash script that displays numbers from 1 to 20 and:
counter=0

while [ $counter -lt 20 ]; do
	echo $counter
    case $counter in
        4) echo "and then bad luck from China";;
        9) echo "and then bad luck from Japan";;
        17) echo "and then bad luck from Italy";;
    esac
	((counter++))
done

